[workspace]
resolver = "2"
members = [
  "nilinit",
  "services/nild",
  "services/nilkeyd",
  "services/nilandroidd",
  "services/nilstore",
  "services/notifyd",
  "services/nilimed",
  "services/inputd",
  "services/powerd",
  "services/crashd",
  "services/camerad",
  "services/authd",
  "services/nilttsd",
  "services/vpnd",
  "services/dnsd",
  "services/backupd",
  "services/btd",
  "services/niltrace",
  "services/nilperf",
  "services/thermald",
  "services/alarmd",
  "services/nilwdt",
  "services/logd",
  "services/clipd",
  "services/nilupd",
  "services/audiod",
  "services/mediad",
  "services/userd",
  "services/nilsr",
  "services/ntpd",
  "services/netd",
  "runtime/nilrt",
  "runtime/nilui",
  "runtime/nilui-gpu",
  "runtime/nilhal",
  "runtime/nilsd",
  "runtime/nilbus-client",
  "runtime/nilandroid-client",
  "runtime/nilnotify",
  "runtime/nilcam",
  "runtime/nilaudio",
  "runtime/nilauth",
  "softbus",
  "shell",
  "nilgui",
  "nilsim",
  "pkg/nilpkg",
  "apps/hello",
  "apps/busdemo",
  "apps/animdemo",
  "apps/lockscreen",
  "apps/bridgedemo",
  "apps/oobe",
  "apps/launcher",
  "apps/settings",
  "apps/camdemo",
  "apps/clockwidget",
  "tools/nilup",
  "tools/nilstore",
  "android/agent",
]

[profile.release]
lto = true
strip = true
panic = "abort"
opt-level = "z"
codegen-units = 1
